server.port: 8762
spring.application.name: zuul-gateway
eureka.client.service-url.default-zone: ${vcap.services.pwa-eureka-service.credentials.uri}/eureka/

zuul.routes:
  gallery-service:
    url: http://localhost:8100
    path: /**
    service-id: gallery-service
    
  auth-service:
    url: http://localhost:8600
    path: /auth/**
    service-id: auth-service
    strip-prefix: false
    .sensitive-headers: Cookie,Set-Cookie
