name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        echo "Build for spring-websockets-amqp project"
        mvn -B package --file spring-websockets-amqp/consumer/pom.xml
        mvn -B package --file spring-websockets-amqp/consumer/pom.xml
        echo "Build for spring-actuator"
        mvn -B package --file spring-actuator/pom.xml
        echo "Build for spring-actuator"
        mvn -B package --file spring-actuator/pom.xml
        echo "Build for spring-boot-admin-ops"
        mvn -B package --file spring-boot-admin-ops/pom.xml
        echo "Build for spring-boot-config"
        mvn -B package --file spring-boot-config/pom.xml
        echo "Build for spring-session-data-redis"
        mvn -B package --file spring-session-data-redis/pom.xml
      
