name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: 
        - mvn -B package --file spring-websockets-amqp/consumer/pom.xml
        - mvn -B package --file spring-websockets-amqp/producer/pom.xml
        - mvn -B package --file spring-actuator/pom.xml
        - mvn -B package --file spring-boot-admin-ops/pom.xml
        - mvn -B package --file spring-boot-config/pom.xml
        - mvn -B package --file spring-cloud-eureka/pom.xml
        - mvn -B package --file spring-session-data-redis/pom.xml
      
